permissions:
  model: role

  roles:
    admin:
      crud: [index, show, create, update, destroy]
      fields: { readable: all, writable: all }
      actions: all
      scope: all
      presenters: all

    editor:
      crud: [index, show]
      fields: { readable: all, writable: [] }
      actions: { allowed: [] }
      scope: all
      presenters: all

    viewer:
      crud: [index, show]
      fields: { readable: [name, label, active], writable: [] }
      actions: { allowed: [] }
      scope: all
      presenters: all

  default_role: viewer
