view_group:
  model: article
  primary: articles
  navigation:
    menu: main
    position: 3
  breadcrumb:
    relation: category
  views:
    - presenter: articles
      label: "Articles"
      icon: file-text
