view_group:
  model: employee
  primary: employees
  navigation:
    menu: main
    position: 8
  breadcrumb:
    relation: department
  views:
    - presenter: employees
      label: "Employees"
      icon: users
