view_group:
  model: project
  primary: projects
  navigation:
    menu: main
    position: 9
  breadcrumb:
    relation: department
  views:
    - presenter: projects
      label: "Projects"
      icon: briefcase
