view_group:
  model: showcase_field
  primary: showcase_fields_table
  views:
    - presenter: showcase_fields_table
      label: "Table View"
      icon: grid
    - presenter: showcase_fields_card
      label: "Card View"
      icon: layout
