view_group:
  model: company
  primary: company
  navigation:
    menu: main
    position: 1
  views:
    - presenter: company
      label: "Detailed"
      icon: maximize
    - presenter: company_short
      label: "Short"
      icon: list
