view_group:
  model: company
  primary: company
  navigation: false
  views:
    - presenter: company
      label: "Detailed"
      icon: maximize
    - presenter: company_short
      label: "Short"
      icon: list
