view_group:
  model: contact
  primary: contact_admin
  navigation:
    menu: main
    position: 2
  views:
    - presenter: contact_admin
      label: "Detailed"
      icon: maximize
    - presenter: contact_short
      label: "Short"
      icon: list
