view_group:
  model: contact
  primary: contact
  navigation: false
  breadcrumb:
    relation: company
  views:
    - presenter: contact
      label: "Detailed"
      icon: maximize
    - presenter: contact_short
      label: "Short"
      icon: list
