view_group:
  model: deal
  primary: deal
  navigation: false
  breadcrumb:
    relation: company
  views:
    - presenter: deal
      label: "Detailed"
      icon: maximize
    - presenter: deal_short
      label: "Short"
      icon: list
