view_group:
  model: deal
  primary: deal
  navigation:
    menu: main
    position: 3
  views:
    - presenter: deal
      label: "Detailed"
      icon: maximize
    - presenter: deal_short
      label: "Short"
      icon: list
