view_group:
  model: deal
  primary: deal_pipeline
  navigation:
    menu: main
    position: 4
  breadcrumb:
    relation: company
  views:
    - presenter: deal_pipeline
      label: "Pipeline"
      icon: bar-chart
